export interface StateRefundInfo {
  name: string;
  code: string;
  url: string | null; // null means NONE (no refund status or no income tax)
  isNone?: boolean;
}

export const stateRefundData: StateRefundInfo[] = [
  { name: 'Alabama', code: 'AL', url: 'https://myalabamataxes.alabama.gov/' },
  { name: 'Alaska', code: 'AK', url: null, isNone: true },
  { name: 'Arizona', code: 'AZ', url: 'https://aztaxes.gov/Home/CheckRefund' },
  { name: 'Arkansas', code: 'AR', url: 'https://atar.dfa.arkansas.gov/' },
  { name: 'California', code: 'CA', url: 'https://webapp.ftb.ca.gov/refund/login' },
  { name: 'Colorado', code: 'CO', url: 'https://www.colorado.gov/revenueonline/' },
  { name: 'Connecticut', code: 'CT', url: 'https://drsindtax.ct.gov/AUT/welcomeindividual.aspx' },
  { name: 'Delaware', code: 'DE', url: 'https://dorweb.revenue.delaware.gov/scripts/refinq/refinq.dll' },
  { name: 'District of Columbia', code: 'DC', url: 'https://mytax.dc.gov/' },
  { name: 'Florida', code: 'FL', url: null, isNone: true },
  { name: 'Georgia', code: 'GA', url: 'https://gtc.dor.ga.gov/' },
  { name: 'Hawaii', code: 'HI', url: 'https://hitax.hawaii.gov/' },
  { name: 'Idaho', code: 'ID', url: 'https://tax.idaho.gov/i-1039.cfm' },
  { name: 'Illinois', code: 'IL', url: 'https://mytax.illinois.gov/' },
  { name: 'Indiana', code: 'IN', url: 'https://intime.dor.in.gov/' },
  { name: 'Iowa', code: 'IA', url: 'https://govconnect.iowa.gov/' },
  { name: 'Kansas', code: 'KS', url: 'https://www.kdor.ks.gov/Apps/Individual/RefundStatus' },
  { name: 'Kentucky', code: 'KY', url: 'https://refund.ky.gov/' },
  { name: 'Louisiana', code: 'LA', url: 'https://latap.revenue.louisiana.gov/' },
  { name: 'Maine', code: 'ME', url: 'https://portal.maine.gov/refundstatus/refund' },
  { name: 'Maryland', code: 'MD', url: 'https://interactive.marylandtaxes.gov/INDIV/RefundStatus/default.asp' },
  { name: 'Massachusetts', code: 'MA', url: 'https://mtc.dor.state.ma.us/mtc/_/' },
  { name: 'Michigan', code: 'MI', url: 'https://etreas.michigan.gov/iit/index' },
  { name: 'Minnesota', code: 'MN', url: 'https://www.mndor.state.mn.us/tp/refund' },
  { name: 'Mississippi', code: 'MS', url: 'https://tap.dor.ms.gov/' },
  { name: 'Missouri', code: 'MO', url: 'https://dor.mo.gov/taxation/return-status/' },
  { name: 'Montana', code: 'MT', url: 'https://tap.dor.mt.gov/' },
  { name: 'Nebraska', code: 'NE', url: 'https://ndr-refundstatus.ne.gov/' },
  { name: 'Nevada', code: 'NV', url: null, isNone: true }, // Usually no income tax
  { name: 'New Hampshire', code: 'NH', url: null, isNone: true },
  { name: 'New Jersey', code: 'NJ', url: 'https://www16.state.nj.us/TYTR_TGI_INQ/jsp/prompt.jsp' },
  { name: 'New Mexico', code: 'NM', url: 'https://tap.state.nm.us/Tap/_/' },
  { name: 'New York', code: 'NY', url: 'https://www.tax.ny.gov/pit/file/refund.htm' },
  { name: 'North Carolina', code: 'NC', url: 'https://eservices.dor.nc.gov/wheresmyrefund/' },
  { name: 'North Dakota', code: 'ND', url: 'https://tap.nd.gov/' },
  { name: 'Ohio', code: 'OH', url: 'https://tax.ohio.gov/individual/refund-status' },
  { name: 'Oklahoma', code: 'OK', url: 'https://oktap.tax.ok.gov/' },
  { name: 'Oregon', code: 'OR', url: 'https://revenueonline.dor.oregon.gov/' },
  { name: 'Pennsylvania', code: 'PA', url: 'https://www.doreservices.state.pa.us/Individual/Refund/default.htm' },
  { name: 'Rhode Island', code: 'RI', url: 'https://taxportal.ri.gov/' },
  { name: 'South Carolina', code: 'SC', url: 'https://dor.sc.gov/tax/individual-income/refund-status' },
  { name: 'South Dakota', code: 'SD', url: null, isNone: true },
  { name: 'Tennessee', code: 'TN', url: null, isNone: true },
  { name: 'Texas', code: 'TX', url: null, isNone: true },
  { name: 'Utah', code: 'UT', url: 'https://tap.tax.utah.gov/' },
  { name: 'Vermont', code: 'VT', url: 'https://myvtax.vermont.gov/' },
  { name: 'Virginia', code: 'VA', url: 'https://www.individual.tax.virginia.gov/vtpm/IWeb/' },
  { name: 'Washington', code: 'WA', url: null, isNone: true },
  { name: 'West Virginia', code: 'WV', url: 'https://mytaxes.wvtax.gov/' },
  { name: 'Wisconsin', code: 'WI', url: 'https://tap.revenue.wi.gov/RefundStatus/' },
  { name: 'Wyoming', code: 'WY', url: null, isNone: true },
];
